name: Backend - Build and Push Docker Image

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/backend-docker.yml"
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{github.repository}}/api:latest
            ghcr.io/${{github.repository}}/api:${{ github.sha }}
            ghcr.io/${{github.repository}}/api:${{ github.ref_name }}

      - name: Image digest
        run: |
          echo "✅ Backend image built successfully!"
          echo "📦 Image: ghcr.io/${{ github.repository }}/api"
          echo "🔖 Tags: ${{ steps.meta.outputs.tags }}"
